// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/2/2026, 9:10:52 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/nguye/platform-ai-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/nguye/platform-ai-frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/nguye/platform-ai-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/nguye/platform-ai-frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/nguye/platform-ai-frontend/plugins/**/*.{js,ts,mjs}","C:/Users/nguye/platform-ai-frontend/composables/**/*.{js,ts,mjs}","C:/Users/nguye/platform-ai-frontend/utils/**/*.{js,ts,mjs}","C:/Users/nguye/platform-ai-frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/nguye/platform-ai-frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/nguye/platform-ai-frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/nguye/platform-ai-frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;